### ISSUE TITLE
exclude hacktoberfest

### ISSUE THREAD

**Issue by mrtampan** [veldanava/HacktoberFest2023#40]
kayanya nama repository kena diblokir smaa hacktoberfest

![Screenshot 2023-10-15 160909](https://github.com/veldanava/HacktoberFest2023/assets/33930946/19a68f2b-9526-4128-8c24-b408fbd841ed)

![download (1)](https://github.com/veldanava/HacktoberFest2023/assets/33930946/1ba2207c-bc99-489d-b901-29e01f187759)

**Comment by veldanava** [comment]
Halo
oke makasih open issue nya

Nanti aku cek dulu

**Comment by veldanava** [comment]
done
